name: Python application
permissions: write-all
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: run code
        run: |
          cd workflow
          python actions.py
      - name: commits
        run: |
          git config --local user.email "autoaction@autoaction.com"
          git config --local user.name "[bot]auto-readme"
          git add .
          git commit -m "[bot]auto readme update"

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
